language: groovy
jdk:
- oraclejdk7
sudo: false
branches:
  only:
  - master
before_install:
- wget -q https://raw.githubusercontent.com/AtlasOfLivingAustralia/travis-build-configuration/master/ala_common.sh
- chmod +x ala_common.sh
- source ./ala_common.sh
- ala_travis_grails_setup_env
script:
- ala_travis_grails_build
env:
  global:
  - secure: g3XTAaVYwW8YBXep4OPfOCX0wSvv4tkWrd5jLXk08R6iQfgIJ54T52e1mW+a5yOkpXrb40GVp11UWnl4irEpm4IlbCx/THgEI0Xtkq9pQOJ0hGl2RhvP01VuqPQ8N066nuT5kY09E2a6ezM98H9El7XToeZF0EkAagK/QZ/HwuyQrjicDO5MzVY/xTqFfl0NvX+ILPswN54n8zuKk2u8C4qIktenLI2Jnwr+yJMr/VcdIh/UxNH9vrf897h2sRTIFRpuKkvx669cnKz96Ng3d+7DGiVobaxAbttgVdkwHrzT6fRaHwnvX171Z1F+JP23NP3rRZgLEjbD9xB69Ahl2sdn7+V9tVwLuOqYwA1DChtGpxDRP8yxYygBYgNSKe208m+HJkgTDwbXIQSOY882dqkuc3sePs2Bt2FmMOmZ9+IMrB0e1aLHqLPRPOglZV0lH1ck96gYLoW/ZDwSiXLGCpuwrYxSTGYjECs4YPp0uP10gFFNk/VPbQ9rZ7YzhSIGmMvzzR3oUOnVJcQ3YqAo1n5MCMCeJoLoHhgfhg+bcPXz7CBMLLFA4sj/aPNsVmLp29e6WSVyJxRdGKVeVkAAWht9h6D+tSQQpD2SD9b7yKqmniyJbCi2Jrgd2Nk7JAR1of/OPXWGwTC3THPPd9rGoDVaCL5XHCQH8D6LuyzbhIw=
  - secure: UyuLwtWvWN91tu+mVolOm+PHvJvt5F6SaHTR1Dn2LZKo06d+WWeI2HyxMQ7SwP/eTG1O09OXkItkTGoAXCm7dbM6n6fyFFLurKibnDfhFeV/Yabs6mpn1+GVPLvx61jR2QH5CJa79E4hA3gxz1OzlqgJ1hwbftwSjjqyeRGQ3eIUguwx1F9vVwNWk9Kz2jVLxNTtE3PxXurPr8Gdp4HjzFAl7NlfE+kAJcdV9dAw2vsvE0wik2UhW8e+7xFQlIfIRnnN44YrNBrSLpG0tuMzqVbLHq4K2xOD6cJKkKYEr7Hy+WwBmbr7FiLZns94XYH/zV4fwJ5GFRpBsFiuOol7tHD0kzMlU6Q60WL27CxbndjcaiGKVADZEJ50n1XpM/kIdSqGiaG5Zo7/FVeUmrh6zJJIsmWfvgPeIMLYcV8wwJlBzejNAxBJHbamjanS7QJ9YF+5klNbcOHk9gLEGQ4L1JXL+aCHuTiOQep9K1vUotDroB3imNpUxGVtq6SdTHQPhzUF7l4XD7x6mh6ye0/8ur8F6DwVuk5Xt5VyZtUHDhXMnlAyye4SjAhkniSEZKXq058RevoW2u2aG3enuQcGD071OtPQ/k9/T2H5aVmHj2QsG0zLRRG+Bh53OiHMh7bxeLEWC8g+W0cRy3YiLvTALiooB82DjyRyjOQLF89jViI=
